name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.16.0'

      - name: Install
        run: npm install

      - name: Build and Deploy React app to Github Pages
        run: omkartapale/react-deployment-gh-pages@v1.0.0

      

      